import { Header } from '../components/layout/Header';
import { Footer } from '../components/layout/Footer';
import { Link } from 'react-router-dom';

const ROLE_FEATURES = [
  {
    role: 'Residents',
    id: 'residents',
    description: 'Experience a seamless living experience with fast payments, easy visitor management, and direct communication channels.',
    color: 'primary',
    features: [
      {
        icon: 'payments',
        title: 'UPI Payments',
        desc: 'Pay maintenance and utility bills instantly using any UPI app with automated receipts.'
      },
      {
        icon: 'qr_code_scanner',
        title: 'QR Code Passes',
        desc: 'Generate one-time QR codes for guests to ensure secure and hassle-free entry.'
      },
      {
        icon: 'campaign',
        title: 'Community Noticeboard',
        desc: 'Stay updated with the latest society announcements, polls, and community events.'
      }
    ]
  },
  {
    role: 'Owners',
    id: 'owners',
    description: 'Exclusive tools designed for property owners. Track your investment ROI, manage multiple units, and oversee operations.',
    color: 'secondary',
    features: [
      {
        icon: 'monitoring',
        title: 'Global Dashboard',
        desc: 'Gain a macroscopic view of your entire real estate portfolio. Monitor active leases and review occupancy rates.'
      },
      {
        icon: 'inventory_2',
        title: 'Digital Vault',
        desc: 'Securely store and retrieve digital copies of deeds, contracts, and legal documentation.'
      },
      {
        icon: 'account_balance_wallet',
        title: 'Expense Tracking',
        desc: 'Automated ledger for tax season preparation and monthly profit-loss statements.'
      }
    ]
  },
  {
    role: 'Admins',
    id: 'admins',
    description: 'Empower your society administrators with unparalleled oversight. Manage community funds, approve user access, and control bookings.',
    color: 'tertiary',
    features: [
      {
        icon: 'account_balance',
        title: 'Fund Management',
        desc: 'Oversee society treasuries, automate monthly billing cycles, and track outstanding maintenance dues.'
      },
      {
        icon: 'admin_panel_settings',
        title: 'Access Control',
        desc: 'Review and approve new resident registrations. Manage roles and permissions for owners, tenants, and staff.'
      },
      {
        icon: 'event_available',
        title: 'Facility Booking',
        desc: 'Manage reservations for common areas like clubhouses, gyms, and party halls. Set rules and dynamic pricing.'
      }
    ]
  },
  {
    role: 'Security',
    id: 'security',
    description: 'Equip your security personnel with high-speed, intuitive tools designed for rapid execution at the gate.',
    color: 'error',
    features: [
      {
        icon: 'verified_user',
        title: 'Instant QR Verification',
        desc: 'Scan visitor passes generated by residents for instantaneous, frictionless entry at the main gate.'
      },
      {
        icon: 'directions_car',
        title: 'Vehicle Tracking',
        desc: 'Log incoming cabs and delivery vehicles with automatic license plate recognition integration.'
      },
      {
        icon: 'notifications_active',
        title: 'Emergency Broadcast',
        desc: 'Trigger community-wide silent alarms or fire alerts directly from the guard terminal in case of emergencies.'
      }
    ]
  }
];

export function Features() {
  return (
    <div className="bg-background text-on-surface font-body selection:bg-primary/30 selection:text-primary overflow-x-clip min-h-screen bg-mesh">
      <Header />

      <main className="pt-32 pb-24 space-y-32">
        {/* Hero Section */}
        <section className="relative px-6 md:px-8 lg:px-16 text-center">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-3/4 h-[500px] bg-primary/5 blur-[140px] rounded-full pointer-events-none" />
          
          <div className="max-w-5xl mx-auto text-center relative z-10 space-y-6">
            <h1 className="text-5xl md:text-7xl font-headline font-extrabold tracking-tighter leading-[1.1]">
              Tailored Features for <br />
              <span className="text-primary italic text-glow">Every User</span>
            </h1>
            <p className="text-on-surface-variant opacity-80 text-lg max-w-2xl mx-auto leading-relaxed">
              Discover how BookIt empowers residents, owners, admins, and security personnel with powerful, intuitive tools.
            </p>
            
            {/* Quick nav */}
            <div className="flex flex-wrap justify-center gap-3 pt-8">
              {ROLE_FEATURES.map((group) => (
                <a
                  key={group.id}
                  href={`#${group.id}`}
                  className="px-6 py-2 rounded-full bg-surface-container-low hover:bg-surface-container transition-colors text-xs font-label uppercase tracking-widest text-on-surface"
                >
                  {group.role}
                </a>
              ))}
            </div>
          </div>
        </section>

        {/* Feature Segments */}
        <section className="px-6 md:px-8 lg:px-16 space-y-32">
          {ROLE_FEATURES.map((group, index) => {
            const isEven = index % 2 === 0;
            const colorClass = 
              group.color === 'primary' ? 'text-primary bg-primary/10' :
              group.color === 'secondary' ? 'text-secondary bg-secondary/10' :
              group.color === 'tertiary' ? 'text-tertiary bg-tertiary/10' :
              'text-error bg-error/10';

            const textColorClass = 
              group.color === 'primary' ? 'text-primary' :
              group.color === 'secondary' ? 'text-secondary' :
              group.color === 'tertiary' ? 'text-tertiary' :
              'text-error';

            return (
              <div key={group.id} id={group.id} className="max-w-7xl mx-auto scroll-mt-32">
                <div className={`flex flex-col lg:flex-row gap-16 lg:gap-24 items-center ${isEven ? '' : 'lg:flex-row-reverse'}`}>
                  
                  {/* Text Content */}
                  <div className="flex-1 space-y-8">
                    <div className="space-y-4">
                      <span className={`inline-flex items-center gap-2 text-[10px] font-label tracking-[0.2em] uppercase px-4 py-1.5 rounded-full ${colorClass}`}>
                        For {group.role}
                      </span>
                      <h2 className="text-4xl md:text-5xl font-headline font-bold tracking-tight">
                        {group.role}
                      </h2>
                      <p className="text-on-surface-variant opacity-80 text-base leading-relaxed max-w-lg">
                        {group.description}
                      </p>
                    </div>

                    <div className="space-y-8 pt-4">
                      {group.features.map((feature, fIndex) => (
                        <div key={fIndex} className="flex gap-4">
                          <div className={`mt-1 shrink-0 w-10 h-10 rounded-xl bg-surface-container flex items-center justify-center ${textColorClass}`}>
                            <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>{feature.icon}</span>
                          </div>
                          <div>
                            <h3 className="text-lg font-headline font-bold mb-1">{feature.title}</h3>
                            <p className="text-on-surface-variant opacity-70 text-sm leading-relaxed">
                              {feature.desc}
                            </p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Visual / Abstract Representation */}
                  <div className="flex-1 w-full relative">
                    <div className="aspect-square max-h-[500px] w-full mx-auto relative">
                      {/* Ambient Glow */}
                      <div className={`absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-64 h-64 blur-[100px] rounded-full pointer-events-none opacity-40 ${
                         group.color === 'primary' ? 'bg-primary' :
                         group.color === 'secondary' ? 'bg-secondary' :
                         group.color === 'tertiary' ? 'bg-tertiary' :
                         'bg-error'
                      }`} />
                      
                      {/* Realistic Data Cards or Scanner */}
                      <div className="absolute inset-0 flex items-center justify-center">
                        {group.id === 'security' ? (
                           <div className="relative w-full max-w-sm h-96 bg-surface-container-high rounded-[2.5rem] shadow-2xl overflow-hidden border border-outline-variant/20 flex flex-col items-center justify-center p-8">
                              {/* Scanner Background */}
                              <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCI+PGNpcmNsZSBjeD0iMSIgY3k9IjEiIHI9IjEiIGZpbGw9InJnYmEoMTI4LDEyOCwxMjgsMC4yKSIvPjwvc3ZnPg==')] opacity-50" />
                              
                              {/* Scanner Frame */}
                              <div className="relative z-10 w-48 h-48 border-2 border-primary/40 rounded-3xl overflow-hidden flex items-center justify-center bg-inverse-surface/10 backdrop-blur-sm relative">
                                <span className="material-symbols-outlined text-primary/50" style={{ fontSize: '80px' }}>qr_code_2</span>
                                
                                {/* Animated Scanning Line */}
                                <div className="absolute top-0 left-0 w-full h-[2px] bg-primary shadow-[0_0_15px_var(--color-primary)] animate-[scan_2s_ease-in-out_infinite]" />
                              </div>
                              
                              {/* Scanner Text */}
                              <div className="relative z-10 mt-8 text-center">
                                <div className="text-primary font-headline font-bold tracking-widest uppercase text-sm mb-2 animate-pulse">Scanning Pass...</div>
                                <div className="text-on-surface-variant text-xs opacity-80">Align QR code within the frame</div>
                              </div>
                           </div>
                        ) : (
                           <div className="relative w-full max-w-sm h-96">
                             {/* Top Right Card */}
                             <div className="absolute top-0 right-0 w-4/5 bg-surface-container-low rounded-[2rem] shadow-2xl p-6 transform rotate-3 hover:rotate-0 transition-transform duration-500 border border-outline-variant/20 flex flex-col justify-center min-h-[160px]">
                                <div className={`w-12 h-12 rounded-2xl flex items-center justify-center mb-4 bg-surface-container ${textColorClass}`}>
                                  <span className="material-symbols-outlined" style={{ fontSize: '24px' }}>{group.features[1].icon}</span>
                                </div>
                                <div className="space-y-1">
                                  <div className="text-on-surface font-headline font-bold text-lg leading-tight">{group.features[1].title}</div>
                                  <div className="text-on-surface-variant text-xs leading-relaxed opacity-80 line-clamp-2">{group.features[1].desc}</div>
                                </div>
                             </div>
                             
                             {/* Bottom Left Card */}
                             <div className="absolute bottom-0 left-0 w-4/5 bg-surface-container-highest rounded-[2rem] shadow-2xl p-6 transform -rotate-3 hover:rotate-0 transition-transform duration-500 backdrop-blur-xl border border-outline-variant/30 flex flex-col justify-center min-h-[160px]">
                                <div className="flex items-center gap-4 mb-4">
                                  <div className={`w-10 h-10 rounded-full flex items-center justify-center ${colorClass}`}>
                                     <span className="material-symbols-outlined" style={{ fontSize: '18px' }}>{group.features[0].icon}</span>
                                  </div>
                                  <div>
                                    <div className="text-on-surface font-headline font-bold text-sm leading-tight">{group.features[0].title}</div>
                                    <div className="text-on-surface-variant text-[10px] font-label uppercase tracking-widest opacity-60">Active Module</div>
                                  </div>
                                </div>
                                <div className="text-on-surface-variant text-sm leading-relaxed opacity-80 line-clamp-3">
                                  {group.features[0].desc}
                                </div>
                             </div>
                           </div>
                        )}
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            );
          })}
        </section>

        {/* CTA Section */}
        <section className="px-6 md:px-8 lg:px-16 pt-16">
          <div className="max-w-5xl mx-auto text-center bg-surface-container-low rounded-[3rem] p-12 md:p-20 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-primary/10 blur-[80px] rounded-full pointer-events-none" />
            <div className="absolute bottom-0 left-0 w-64 h-64 bg-secondary/10 blur-[80px] rounded-full pointer-events-none" />
            
            <div className="relative z-10 space-y-6">
              <h2 className="text-3xl md:text-5xl font-headline font-bold tracking-tight max-w-2xl mx-auto leading-tight">
                Join thousands of premium communities
              </h2>
              <p className="text-on-surface-variant opacity-80 text-base max-w-xl mx-auto mb-8">
                The premier operating system for modern luxury estates. Experience the future of property management with BookIt.
              </p>
              
              <Link to="/signup">
                <button className="bg-primary text-background py-4 px-8 rounded-xl font-headline font-bold text-base hover:shadow-[0_0_30px_rgba(115,255,227,0.3)] active:scale-[0.98] transition-all inline-flex items-center gap-2 mt-4">
                  Register society
                  <span className="material-symbols-outlined" style={{ fontSize: '18px' }}>arrow_forward</span>
                </button>
              </Link>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
